name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: black-alpha-460514-n2
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Activate service account & Docker login
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          gcloud config set account chatbot@black-alpha-460514-n2.iam.gserviceaccount.com
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          echo $ACCESS_TOKEN | docker login -u oauth2accesstoken --password-stdin https://asia-northeast3-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t asia-northeast3-docker.pkg.dev/black-alpha-460514-n2/chatbot/chatbot:latest .

      - name: Push Docker image
        run: |
          docker push asia-northeast3-docker.pkg.dev/black-alpha-460514-n2/chatbot/chatbot:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy chatbot-service \
            --image asia-northeast3-docker.pkg.dev/black-alpha-460514-n2/chatbot/chatbot:latest \
            --platform managed \
            --region asia-northeast3 \
            --allow-unauthenticated \
            --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }},GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }},SOLAR_API_KEY=${{ secrets.SOLAR_API_KEY }}
